config/routes.rb
VetApp::Application.routes.draw do
  resources :appointments

  resources :pets

  resources :customers

  resources :receptionists

  resources :doctors

  root :to => 'appointments#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :customer
  has_many :appointments
  has_many :doctors, through: :appointments
  attr_accessible :age, :breed, :name, :type, :weight

  validates :name, :age, :weight, presence: true
  validates :type, inclusion: {in: %w(dog cat bird)}
  validates :name, :breed, length: {maximum: 35}
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/new
  # GET /pets/new.json
  def new
    @pet = Pet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(params[:pet])

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render json: @pet, status: :created, location: @pet }
      else
        format.html { render action: "new" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.json
  def update
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Breed</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pets.each do |pet| %>
  <tr>
    <td><%= pet.name %></td>
    <td><%= pet.type %></td>
    <td><%= pet.breed %></td>
    <td><%= pet.age %></td>
    <td><%= pet.weight %></td>
    <td><%= pet.customer %></td>
    <td><%= link_to 'Show', pet %></td>
    <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
    <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pet.name %>
</p>

<p>
  <b>Type:</b>
  <%= @pet.type %>
</p>

<p>
  <b>Breed:</b>
  <%= @pet.breed %>
</p>

<p>
  <b>Age:</b>
  <%= @pet.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @pet.weight %>
</p>

<p>
  <b>Customer:</b>
  <%= @pet.customer %>
</p>


<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>