config/routes.rb
VetApp::Application.routes.draw do
  resources :appointments

  resources :pets

  resources :customers

  resources :receptionists

  resources :doctors

  root :to => 'appointments#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :address, :city, :name, :school, :state, :practice_started, :zip
  has_many :appointments
  has_many :pets, through: :appointments
  validates :name, presence: true 
  validates :name, length: {maximum: 35}
  validates :zip,  length: {is: 5}
  validate :practice_started_not_100

  def years_in_practice
    Time.now.year - self.practice_started.year
  end

  def practice_started_not_100
     if Time.now.year - self.practice_started.year > 100
        errors.add(:practice_started, " this cannot be more than 100 years ago")
     end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :practice_started %><br />
    <%= f.date_select :practice_started %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<span class="label label-important"><h1>Listing doctors</h1></span>

<table class="table table-condensed table-hover table-striped">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>School</th>
    <th>Years practice</th>
    <th></th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.name %></td>
    <td><%= doctor.address %></td>
    <td><%= doctor.city %></td>
    <td><%= doctor.state %></td>
    <td><%= doctor.zip %></td>
    <td><%= doctor.school %></td>
    <td><%= doctor.years_in_practice %></td>
    <td><%= link_to '', edit_doctor_path(doctor), class: 'icon-pencil' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @doctor.name %>
</p>

<p>
  <b>Address:</b>
  <%= @doctor.address %>
</p>

<p>
  <b>City:</b>
  <%= @doctor.city %>
</p>

<p>
  <b>State:</b>
  <%= @doctor.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @doctor.zip %>
</p>

<p>
  <b>School:</b>
  <%= @doctor.school %>
</p>

<p>
  <b>Years practiced:</b>
  <%= @doctor.years_in_practice %>
</p>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>