config/routes.rb
VetApp::Application.routes.draw do
  resources :appointments

  resources :pets

  resources :customers

  resources :receptionists

  resources :doctors

  root :to => 'appointments#index'

end

app/models/receptionist.rb
class Receptionist < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  # GET /receptionists
  # GET /receptionists.json
  def index
    @receptionists = Receptionist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receptionists }
    end
  end

  # GET /receptionists/1
  # GET /receptionists/1.json
  def show
    @receptionist = Receptionist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receptionist }
    end
  end

  # GET /receptionists/new
  # GET /receptionists/new.json
  def new
    @receptionist = Receptionist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receptionist }
    end
  end

  # GET /receptionists/1/edit
  def edit
    @receptionist = Receptionist.find(params[:id])
  end

  # POST /receptionists
  # POST /receptionists.json
  def create
    @receptionist = Receptionist.new(params[:receptionist])

    respond_to do |format|
      if @receptionist.save
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully created.' }
        format.json { render json: @receptionist, status: :created, location: @receptionist }
      else
        format.html { render action: "new" }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receptionists/1
  # PUT /receptionists/1.json
  def update
    @receptionist = Receptionist.find(params[:id])

    respond_to do |format|
      if @receptionist.update_attributes(params[:receptionist])
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receptionists/1
  # DELETE /receptionists/1.json
  def destroy
    @receptionist = Receptionist.find(params[:id])
    @receptionist.destroy

    respond_to do |format|
      format.html { redirect_to receptionists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/views/receptionists/_form.html.erb
<%= form_for(@receptionist) do |f| %>
  <% if @receptionist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receptionist.errors.count, "error") %> prohibited this receptionist from being saved:</h2>

      <ul>
      <% @receptionist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receptionists/edit.html.erb
<h1>Editing receptionist</h1>

<%= render 'form' %>

<%= link_to 'Show', @receptionist %> |
<%= link_to 'Back', receptionists_path %>

app/views/receptionists/index.html.erb
<h1>Listing receptionists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receptionists.each do |receptionist| %>
  <tr>
    <td><%= receptionist.name %></td>
    <td><%= receptionist.email %></td>
    <td><%= link_to 'Show', receptionist %></td>
    <td><%= link_to 'Edit', edit_receptionist_path(receptionist) %></td>
    <td><%= link_to 'Destroy', receptionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receptionist', new_receptionist_path %>

app/views/receptionists/new.html.erb
<h1>New receptionist</h1>

<%= render 'form' %>

<%= link_to 'Back', receptionists_path %>

app/views/receptionists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @receptionist.name %>
</p>

<p>
  <b>Email:</b>
  <%= @receptionist.email %>
</p>


<%= link_to 'Edit', edit_receptionist_path(@receptionist) %> |
<%= link_to 'Back', receptionists_path %>